# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 20:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsmDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm', models.IntegerField(max_length=5)),
                ('asmdem16', models.FloatField()),
                ('asmrep16', models.FloatField()),
                ('asmdemwasted16', models.FloatField()),
                ('asmrepwasted16', models.FloatField()),
                ('asmtot16', models.FloatField()),
                ('asmdem14', models.FloatField()),
                ('asmrep14', models.FloatField()),
                ('asmdemwasted14', models.FloatField()),
                ('asmrepwasted14', models.FloatField()),
                ('asmtot14', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
