# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asmdistricts',
            name='asm',
            field=models.IntegerField(),
        ),
    ]
